version: "3.9"
services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - bridge
    depends_on:
      - react-app
  react-app:
    build:
      context: ./react_app
      dockerfile: ./Dockerfile
    volumes:
      - ./react_app/src:/user/src/react_app/src
    container_name: react-app
    networks:
      bridge:
        aliases:
          - react-app
  flask-auth:
    build:
      context: ./flask_api
      dockerfile: Dockerfile
    container_name: flask-auth
    environment:
      FLASK_APP: "/var/www/flask_api/create_app.py"
      FLASK_ENV: "development"
    volumes:
      - "./:/var/www:rw"
    networks:
      bridge:
        aliases:
          - flask-app
  mongo-auth:
    image: mongo
    networks:
      - bridge
networks:
  bridge: